model:
  embed_size: 128
  hidden_size: 512

data:
  file_path: "data/covid19-faq.txt"
  portion_size: 200
  iters_per_step: 32

experiment:
  lr: 0.005

trainer:
  gpus: [1]
  max_epochs: 20
  monitor: "train_loss"
  mode: "min"

app:
  name: "2_Character_Generation_with_LSTM"
  logs_dir: "logs"
  manual_seed: 1234
